#!/usr/bin/python
######################################################################
# This is a short script that serves
# as a current work-around to make sure
# omegaveto and other MATLAB binaries have the
# source file in the "inputfiles" folder.
# The script copies the MATLAB source file
# from the packaged bin/inputfiles/ folder and
# places it in the inputfiles/ folder
# of the working directory. The script 
# can be called on its own; however, this
# is generally unnecessary, as it is
# called automatically from within bcvSetup_unv
#####################################################################
import os
import sys
import shutil
import re
import optparse
import os.path
import re

from bcv import git_version

cmd = 'echo $BCV_PREFIX > bcvpath.txt'
callStr = str(os.system(cmd))

pathfile = open('bcvpath.txt','r')

path = pathfile.readline()

pathfile.close()

path = path.strip('\n')
path = path + "/bin/inputfiles/"
#print path 

srcfile = path + 'MatlabSetup_R2008a_glnxa64.sh'

#print srcfile

shutil.copy(srcfile, 'inputfiles/MatlabSetup_R2008a_glnxa64.sh')
