#!/usr/bin/python

import os
import sys
import shutil
import os.path
import optparse

import ConfigParser

from bcv import git_version

#-------------------------------------------

parser = optparse.OptionParser(usage=__doc__,version=git_version.verbose_msg)

parser.add_option("-i", "--ini_file",
                    help="Path to the .ini file used. Required.")
parser.add_option("-o", "--omicron_tag",
                    help="Omicron file tag.",default = "_Omicron")
parser.add_option("-I", "--sel_ifo",
                    help="IFO selection.",default = "L1")

opts, args = parser.parse_args()

#-------------------------------------------

cp = ConfigParser.ConfigParser()

cp.read(opts.ini_file)
root_dir = cp.get("input","KW_location")

#------------------------------------------

#root_dir = '/home/detchar/triggers/ER6/L1/'
#tag = '_Omicron'
tag = opts.omicron_tag
dir_list = []

#-----------------------------------------------

config = cp.get("input","configuration_file")

#ifo = "L1"
ifo = opts.sel_ifo

cpA = ConfigParser.ConfigParser()
cpA.read(config)

# select the channels with the right ifo
channels = [c for c in cpA.sections() if c[:2] == ifo]

# -------------------------------------------

for c in channels:
        if (cpA.get(c,"channelType") == "GW") or (cpA.get(c,"channelType") == "fast"):
		ch = c.split(":")
		ch = ch[1]
                dir_list.append(ch)

for dir in dir_list:
	full_path = root_dir + dir + tag
	if (os.path.exists(root_dir + dir + tag)):
		print >> sys.stderr, "Path good: %s"%full_path	
	else:
		print >> sys.stderr, "Path bad: %s"%full_path
