#!/usr/bin/python

import os
import sys
import shutil
import os.path
import optparse
import re
from bcv import git_version

def parse_commandline():
        """
        Parse the options given on the command-line.
        """
        parser = optparse.OptionParser(usage = __doc__,version=git_version.verbose_msg)

        parser.add_option("-f", "--infile", default=None,
                      help="File to be cleaned.")

        opts, args = parser.parse_args()

        return opts

#configs = os.listdir('configs')
opts = parse_commandline()
clfile = opts.infile

file = open(clfile, 'r')
lines = file.read()
lines = lines.replace('~','')	
file.close()
file = open(clfile, 'w')
file.write(lines)
file.close()
